import { Category, Listing } from "@/lib/types/domain";

// Datos de prueba para desarrollo local, sin depender de Supabase todavia.
// La forma de estos objetos espeja 1:1 el esquema de supabase/migrations/0001_init.sql
// para que cambiar a datos reales despues sea solo cambiar la fuente, no la forma.

export const CATEGORIES: Category[] = [
  { id: "cat-molderia", slug: "molderia", name: "Moldería", parentId: null, sortOrder: 1 },
  { id: "cat-confeccion", slug: "confeccion", name: "Confección", parentId: null, sortOrder: 2 },
  { id: "cat-tejido", slug: "tejido", name: "Tejido plano y de punto", parentId: null, sortOrder: 3 },
  { id: "cat-estampado", slug: "estampado", name: "Estampado", parentId: null, sortOrder: 4 },
  { id: "cat-bordado", slug: "bordado", name: "Bordado", parentId: null, sortOrder: 5 },
  { id: "cat-insumos", slug: "insumos", name: "Insumos y avíos", parentId: null, sortOrder: 6 },
  { id: "cat-maquinaria", slug: "maquinaria", name: "Maquinaria", parentId: null, sortOrder: 7 },
  { id: "cat-servicios", slug: "servicios", name: "Servicios", parentId: null, sortOrder: 8 },
  { id: "cat-indu-mayor", slug: "indumentaria-mayor", name: "Indumentaria por mayor", parentId: null, sortOrder: 9 },
  { id: "cat-indu-menor", slug: "indumentaria-menor", name: "Indumentaria por menor", parentId: null, sortOrder: 10 },
];

const categoryBySlug = (slug: string) => CATEGORIES.find((c) => c.slug === slug)!;

export const LISTINGS: Listing[] = [
  {
    id: "l-1",
    userId: null,
    businessProfileId: "bp-1",
    categoryId: "cat-insumos",
    title: "Gabardina elastizada — rollo completo",
    description:
      "Gabardina elastizada premium, ideal para pantalones y uniformes. Buen caído, no se transparenta. Rollo de 80 metros, se corta desde 5m.",
    attributes: { tipo_tejido: "Gabardina elastizada", ancho: "1.50m", composicion: "97% algodón 3% elastano" },
    priceWholesale: 3200,
    priceRetail: 4100,
    priceOnRequest: false,
    currencyCode: "ARS",
    city: "Avellaneda",
    province: "Buenos Aires",
    countryCode: "AR",
    status: "activo",
    createdAt: "2026-08-20T10:00:00Z",
    expiresAt: "2026-10-19T10:00:00Z",
    images: [{ id: "img-1", listingId: "l-1", storagePath: "/placeholder-fabric-1.jpg", position: 0 }],
    category: categoryBySlug("insumos"),
    businessProfile: {
      id: "bp-1",
      userId: "u-1",
      businessName: "Textiles Riachuelo",
      description: "Mayorista de telas para indumentaria hace 15 años.",
      verificationStatus: "sin_verificar",
      city: "Avellaneda",
      province: "Buenos Aires",
      contactPhone: "+54 11 5555-0101",
      socialLinks: { instagram: "https://instagram.com/textilesriachuelo" },
    },
  },
  {
    id: "l-2",
    userId: "u-2",
    businessProfileId: null,
    categoryId: "cat-maquinaria",
    title: "Máquina overlock industrial usada — Siruba",
    description:
      "Overlock 4 hilos, funcionando perfecto, service reciente. Vendo por cierre de taller. Se puede ver funcionando.",
    attributes: { marca: "Siruba", estado: "usada", años_uso: "5" },
    priceWholesale: null,
    priceRetail: 380000,
    priceOnRequest: false,
    currencyCode: "ARS",
    city: "Once",
    province: "CABA",
    countryCode: "AR",
    status: "activo",
    createdAt: "2026-08-22T14:30:00Z",
    expiresAt: "2026-10-21T14:30:00Z",
    images: [{ id: "img-2", listingId: "l-2", storagePath: "/placeholder-machine-1.jpg", position: 0 }],
    category: categoryBySlug("maquinaria"),
    businessProfile: null,
  },
  {
    id: "l-3",
    userId: null,
    businessProfileId: "bp-3",
    categoryId: "cat-estampado",
    title: "Servicio de estampado por sublimación — cualquier cantidad",
    description:
      "Estampamos remeras, buzos y telas por metro. Trabajamos con diseño propio o tuyo. Entrega en 48-72hs según volumen.",
    attributes: { tecnica: "Sublimación", minimo: "sin mínimo" },
    priceWholesale: null,
    priceRetail: null,
    priceOnRequest: true,
    currencyCode: "ARS",
    city: "Rosario",
    province: "Santa Fe",
    countryCode: "AR",
    status: "activo",
    createdAt: "2026-08-23T09:15:00Z",
    expiresAt: "2026-10-22T09:15:00Z",
    images: [{ id: "img-3", listingId: "l-3", storagePath: "/placeholder-print-1.jpg", position: 0 }],
    category: categoryBySlug("estampado"),
    businessProfile: {
      id: "bp-3",
      userId: "u-3",
      businessName: "Estampados del Litoral",
      description: null,
      verificationStatus: "sin_verificar",
      city: "Rosario",
      province: "Santa Fe",
      contactPhone: "+54 341 555-0303",
      socialLinks: {},
    },
  },
  {
    id: "l-4",
    userId: "u-4",
    businessProfileId: "bp-4",
    categoryId: "cat-molderia",
    title: "Base de moldería digital — talles 38 al 56 (formato DXF)",
    description:
      "Base de moldería femenina escalada, lista para usar en cualquier plotter. Incluye remera, pantalón y vestido base.",
    attributes: { formato: "DXF / AAMA", talles: "38 a 56" },
    priceWholesale: 15000,
    priceRetail: 18000,
    priceOnRequest: false,
    currencyCode: "ARS",
    city: "Córdoba",
    province: "Córdoba",
    countryCode: "AR",
    status: "activo",
    createdAt: "2026-08-24T08:00:00Z",
    expiresAt: "2026-10-23T08:00:00Z",
    images: [{ id: "img-4", listingId: "l-4", storagePath: "/placeholder-pattern-1.jpg", position: 0 }],
    category: categoryBySlug("molderia"),
    businessProfile: {
      id: "bp-4",
      userId: "u-4",
      businessName: "Moldería Sur",
      description: "Moldería digital profesional para marcas e independientes.",
      verificationStatus: "sin_verificar",
      city: "Córdoba",
      province: "Córdoba",
      contactPhone: null,
      socialLinks: { instagram: "https://instagram.com/molderiasur" },
    },
  },
  {
    id: "l-5",
    userId: "u-5",
    businessProfileId: null,
    categoryId: "cat-indu-mayor",
    title: "Remeras básicas de algodón — lote por mayor",
    description: "Lote de remeras lisas 100% algodón, colores surtidos, talles S a XL. Mínimo 50 unidades.",
    attributes: { material: "100% algodón", minimo: "50 unidades" },
    priceWholesale: 2800,
    priceRetail: null,
    priceOnRequest: false,
    currencyCode: "ARS",
    city: "La Plata",
    province: "Buenos Aires",
    countryCode: "AR",
    status: "activo",
    createdAt: "2026-08-21T16:45:00Z",
    expiresAt: "2026-10-20T16:45:00Z",
    images: [{ id: "img-5", listingId: "l-5", storagePath: "/placeholder-shirts-1.jpg", position: 0 }],
    category: categoryBySlug("indumentaria-mayor"),
    businessProfile: null,
  },
  {
    id: "l-6",
    userId: null,
    businessProfileId: "bp-6",
    categoryId: "cat-insumos",
    title: "Cierres y broches surtidos — pack x 100",
    description: "Cierres de nylon 20cm a 60cm y broches a presión, colores variados. Ideal para talleres de confección.",
    attributes: { contenido: "100 unidades surtidas" },
    priceWholesale: 9500,
    priceRetail: 12000,
    priceOnRequest: false,
    currencyCode: "ARS",
    city: "Mar del Plata",
    province: "Buenos Aires",
    countryCode: "AR",
    status: "activo",
    createdAt: "2026-08-19T11:20:00Z",
    expiresAt: "2026-10-18T11:20:00Z",
    images: [{ id: "img-6", listingId: "l-6", storagePath: "/placeholder-notions-1.jpg", position: 0 }],
    category: categoryBySlug("insumos"),
    businessProfile: {
      id: "bp-6",
      userId: "u-6",
      businessName: "Mercería El Textil",
      description: null,
      verificationStatus: "sin_verificar",
      city: "Mar del Plata",
      province: "Buenos Aires",
      contactPhone: "+54 223 555-0606",
      socialLinks: {},
    },
  },
];
